# Generated by Django 4.1 on 2022-11-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0006_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll_app.question'),
        ),
    ]
